### ISSUE TITLE
Can I use in isaopen area?

### ISSUE THREAD

**Issue by jflmateusnassar** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#111]
I'm studying and doing tests with EZUIKit-JavaScript and I noticed that there are two versions.
The [EZUIKit-JavaScript](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript) version works with "areaDomain": "https://isaopen.ezvizlife.com". I did some tests and everything worked correctly.
But this version [EZUIKit-JavaScript-npm](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm) does not work with "areaDomain": "https://isaopen.ezvizlife.com"
I don't know if I'm doing something wrong because I'm starting to study about this recently.
Is there any way to make [EZUIKit-JavaScript-npm](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm) work with "areaDomain": "https://isaopen.ezvizlife.com"?

**Comment by samuelkoes** [comment]
I am now developing in the eu area. I have an access token taken from ieuopen.ezvizlife.com, using url ezopen://open.ys7.com/{serial number}/1.live , and can't access the device. My feeling is that, this is a domain issue. So, if someone can give some pointers about this, will be great :)

我现在在欧盟地区发展。 我有一个从 ieuopen.ezvizlife.com 获取的访问令牌，使用 url ezopen://open.ys7.com/{serial number}/1.live ，但无法访问该设备。 我的感觉是，这是一个域问题。 所以，如果有人能就此提出一些建议，那就太好了:)

**Comment by jflmateusnassar** [comment]
After much insistence I figured out how to make urls from other areas work and in your case it would look like this:

`var player = new EZUIKit.EZUIKitPlayer({`
`    id: 'video-container2',`
`    accessToken: document.getElementById("token").value,`
`    //if don't exists verification code the url is ezopen://open.ezviz.com/{serial number}/1.live`
`    url: "ezopen://{verification code}@open.ezviz.com/{serial number}/1.live",`
`    template: 'mobileLive',`
`    plugin: ['talk'],`
`    width: 375,`
`    height: 210,`
`    env:{`
`    	domain: "https://ieuopen.ezvizlife.com"`
`    }`
`  });`

**Comment by samuelkoes** [comment]
> 

Thanks man, I will try this out! Btw, I tried getting access token via the HTTP interface https://open.ezvizlife.com/api/lapp/token/get . It fails, potentially because of the domain as well. Any idea what I need to add other than the appKey and appSecret to make it work?

**Comment by jflmateusnassar** [comment]
You can try this
`https://ieuopen.ezvizlife.com/api/lapp/token/get?appKey=XXXXXXXXXXXXXXXXXXXX&appSecret=YYYYYYYYYYYYYYYYYYYY`

**Comment by jflmateusnassar** [comment]
@samuelkoes 

Do you know if Is there a way to put a 'json' to adapt all texts to another language? In my case in Portuguese or English.
If by 'json' it is not possible, is there any other way?

**Comment by samuelkoes** [comment]
> @samuelkoes
> 
> Do you know if Is there a way to put a 'json' to adapt all texts to another language? In my case in Portuguese or English. If by 'json' it is not possible, is there any other way?

I am not sure if I entirely get what you mean. If it is about the html text, I just google translate these. Otherwise, if you want multiple language feature on a website, this is something we need to develop ourselves...
