### ISSUE TITLE
js源码中的window.fetch未实现所有重构,导致正常调用fetch方法时报错,url.startswith in not a fucntion

### ISSUE THREAD

**Issue by my5201314zwl** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#139]
fetch方法
declare function fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
但是在ezuikit.js中只是重写了window.fetch中fetch第一个参数是url的方法.导致在调用RequestInfo方式实现的fetch,报错.

![WechatIMG34](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/6309339/720b279c-cf74-4256-b63d-a6fa6fe06268)
![WechatIMG45](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/6309339/d3168d01-9b44-4aa0-9c85-dd314ea85a01)

**Comment by Sunrisies** [comment]
怎么解决呢

**Comment by wgbbiao** [comment]
也发现这个问题了。建议起一个别名吧。不要覆盖原有的函数。这样造成的问题太多了。

**Comment by freeshineit** [comment]
请更新 8.0.8 ，问题已修复
