### ISSUE TITLE
standard模式下如何监听插件自带的录象/截图回调，或者触发事件

### ISSUE THREAD

**Issue by MeetKason** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#142]
![CleanShot 2023-09-19 at 10 10 02](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/34768215/7ad15144-07ee-40d7-9462-f20c236979db)

使用了ezuikit-js@7.7.0

**Comment by freeshineit** [comment]
升级到最新版本
