### ISSUE TITLE
vue的demo 对讲功能谷歌浏览器控制台报错，也没有对讲成功

### ISSUE THREAD

**Issue by mrsoz** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#152]
let that = this;
      player = new EZUIKit.EZUIKitPlayer({
        id: "video-container", // 视频容器ID
        accessToken:
          "xxxx",
        url: "xxxx",
        // simple - 极简版; pcLive-pc直播；pcRec-pc回放；mobileLive-移动端直播；mobileRec-移动端回放;security - 安防版;voice-语音版;
        template: 'pcLive',
        plugin: ["talk"], // 加载插件，talk-对讲
        width: 600,
        height: 400,
        handleSuccess:that.initStop,
        handleError:(data)=>console.log('error',data),
        // themeData,
      });
      window.player = player;

**Comment by mrsoz** [comment]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/46982998/57fd38fe-ea73-4629-bc77-a3f01cfd2b2d)

**Comment by mrsoz** [comment]
有人有同样的问题吗？怎么解决的

**Comment by mrsoz** [comment]
设备端没声音

**Comment by bbhxwl** [comment]
我也是，语音开启就出错。

**Comment by Zeng1231cx** [comment]
> 有人有同样的问题吗？怎么解决的

+1

**Comment by mrsoz** [comment]
忘记了怎么解决的了，大概是设备的音频格式要AAC，不是代码方面的问题

**Comment by Zeng1231cx** [comment]
> 忘记了怎么解决的了，大概是设备的音频格式要AAC，不是代码方面的问题

调成AAC后，还是报错，对讲也是不行啊啊

**Comment by bbhxwl** [comment]
> 概是设备的音频格式要AAC，不是代码方面的问题

我已经问了客服解决了。他们的一个小bug
