### ISSUE TITLE
vue项目build后，生产环境报错，本地环境没问题？

### ISSUE THREAD

**Issue by baiqingxia888** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#155]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/89574140/fc3b4254-cafd-44a9-9202-9320df1ba48f)

**Comment by lijiajia3515** [comment]
我发现是需要https访问，但是想用http解决下。
localhost是白名单，看来是最近才出的问题

**Comment by lijiajia3515** [comment]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/22983711/0a80fed9-3471-45ab-a2c6-631c80c4cb00)
