### ISSUE TITLE
v7.7.7 react 严重报错，更换成v7.7.6就可以了

### ISSUE THREAD

**Issue by A-ANing** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#156]
大家注意，7.7.7加载成功无画面，控制台全是红的报错

"ezuikit-js": "^7.7.6",切换成这个版本就可以了

**Comment by JZDKG** [comment]
> 大家注意，7.7.7加载成功无画面，控制台全是红的报错
> 
> "ezuikit-js": "^7.7.6",切换成这个版本就可以了

确实，在浏览器模拟手机的模式下会报
ezuikit.js:52275 Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'https://openstatic.ys7.com/ezuikit_js/v1.2.32/ezuikit_static/v65/v3/js/PlayCtrlWasm/playCtrl1/HasSIMD/DecodeWorker.js' cannot be accessed from origin 'http://localhost:9090'.
    at _0x135c19.createWorker (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52274:925043)
    at new _0x135c19 (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52274:934324)
    at new _0xed4ebc (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52274:968550)
    at InitWasm (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52351:18)
    at eval (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52352:3)
在网页模式下就正常，版本切换到7.7.6就好了

**Comment by A-ANing** [comment]
> > 大家注意，7.7.7加载成功无画面，控制台全是红的报错
> > "ezuikit-js": "^7.7.6",切换成这个版本就可以了
> 
> 确实，在浏览器模拟手机的模式下会报 ezuikit.js:52275 Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'https://openstatic.ys7.com/ezuikit_js/v1.2.32/ezuikit_static/v65/v3/js/PlayCtrlWasm/playCtrl1/HasSIMD/DecodeWorker.js' cannot be accessed from origin 'http://localhost:9090'. at _0x135c19.createWorker (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52274:925043) at new _0x135c19 (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52274:934324) at new _0xed4ebc (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52274:968550) at InitWasm (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52351:18) at eval (webpack-internal:///./node_modules/ezuikit-js/ezuikit.js:52352:3) 在网页模式下就正常，版本切换到7.7.6就好了

我不仅仅是浏览器手机预览模式，什么模式都一样，试了edg，chrome浏览器都一样；
而且那个内存，直接把网页搞崩溃；

**Comment by cuixin3266** [comment]
7.7.8还是没有解决这个bug

**Comment by JZDKG** [comment]
要注意一下锁定版本7.7.8依然有bug,"ezuikit-js": "7.6.3",

**Comment by RyzenVega64** [comment]
我CSDN文章最后有这个注释  https://blog.csdn.net/weixin_46607967/article/details/123632324    确实是只有7.6.3可以  很离谱  工单说无法复现

**Comment by q351941406** [comment]
+1,居然会这样子

**Comment by freeshineit** [comment]
请升级到 7.7.10 或 8.0.0
