### ISSUE TITLE
vue-npm demo版本跨域问题

### ISSUE THREAD

**Issue by lijiajia3515** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#158]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/22983711/f3a024cd-f613-4afe-9bc9-c2d21450e395)

github下载的demo，上传到服务器后访问提示跨域，本地使用localhost正常访问，最近半个月才出现的问题，请教下怎么解决

![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/22983711/d8d4e240-3c10-4ee5-b454-4d92727dcc94)
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/22983711/78c98a3a-887a-4fd1-b97b-10796436a944)

demo链接：http://frontend-test.yiruibim.com/dist/index.html](http://frontend-test.yiruibim.com/dist/index.html)

MacOS 14.1 m1pro
firefox版本：120.0.1
chrome版本：119.0.6045.123（正式版本） (arm64)

**Comment by freeshineit** [comment]
这个是浏览器的安全限制， 你可以配置https 试试看

**Comment by lijiajia3515** [comment]
不用https，需要域名访问，有解决方案吗

**Comment by freeshineit** [comment]
请升级到 7.7.10 或 8.0.0

**Comment by lijiajia3515** [comment]
👍
