### ISSUE TITLE
（附带图片）UIKit 基础版本 升级到 Pro 7.7.X（7.7.6、7.7,7、7.7.8）版本报错：【VideoDecoder is not defined】

### ISSUE THREAD

**Issue by WangYing156** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#163]
【VideoDecoder is not defined】
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/29537824/48b2960b-df7c-45e7-a6fe-75510f2b3bb4)

求解决方法！！！！急急急

**Comment by WangYing156** [comment]
在vue项目中引入7.7.x版本，产生的问题，现象是：黑屏、后台报如上错误

**Comment by liganghui** [comment]
一样的问题  换成v7.6.8正常

**Comment by CJJ3390967102** [comment]
哥们 解决了吗？ 碰到一样的问题了

**Comment by freeshineit** [comment]
请升级到 v7.7.10

**Comment by CJJ3390967102** [comment]
useHardDev: true, //开启高性能模式
开启高性能模式不生效了吗？

**Comment by freeshineit** [comment]
> ```
>     useHardDev: true, //开启高性能模式
> ```
> 
> 开启高性能模式不生效了吗？

需要浏览器支持硬解， 为了兼容， 我们做了自动切换

**Comment by CJJ3390967102** [comment]
> > ```
> >     useHardDev: true, //开启高性能模式
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 开启高性能模式不生效了吗？
> 
> 需要浏览器支持硬解， 为了兼容， 我们做了自动切换

需要这么操作？ 我在浏览器上加了 --enable-features=SharedArrayBuffer  ，感觉还是没有硬解吧

**Comment by CJJ3390967102** [comment]
> > ```
> >     useHardDev: true, //开启高性能模式
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 开启高性能模式不生效了吗？
> 
> 需要浏览器支持硬解， 为了兼容， 我们做了自动切换

需要怎么操作？ 我在浏览器  --enable-features=SharedArrayBuffer 加了这个配置 ，感觉还是没有硬解

**Comment by freeshineit** [comment]
> > > ```
> > >     useHardDev: true, //开启高性能模式
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 开启高性能模式不生效了吗？
> > 
> > 
> > 需要浏览器支持硬解， 为了兼容， 我们做了自动切换
> 
> 需要怎么操作？ 我在浏览器 --enable-features=SharedArrayBuffer 加了这个配置 ，感觉还是没有硬解

--enable-features=SharedArrayBuffer  这个会开启多线程软解， 硬解需要浏览器本身支持才可以。建议使用chrome

**Comment by freeshineit** [comment]
请升级到新版
