### ISSUE TITLE
播放多画面时，某个画面的摄像头可能出现损坏导致无法播放，为什么没有提示

### ISSUE THREAD

**Issue by daiwanxing** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#164]
标题有点没说明白，我举个例子，假设用户希望点击**16画面**看到不同的监控画面，但是恰好有个摄像头坏了，于是**16画面**呈现出来的效果就是有个摄像头画面是黑的，其他15个画面是正常播放的，而坏了的那个画面也没有任何的提示用户这个画面连接失败。

这个是否是目前存在的缺陷？

**Comment by daiwanxing** [comment]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/37327614/1921623e-f3bb-4ae0-9d79-515d9b5b8d28)

**Comment by 2027580893** [comment]
老哥那个多窗口播放是咋搞的

**Comment by 2027580893** [comment]
老哥那个多窗口播放是咋搞的

**Comment by daiwanxing** [comment]
> 老哥那个多窗口播放是咋搞的

后续就是自己实现这种画面分割功能，例如十六画面，就创建 16 个播放器以及16 个窗口 DOM，播放器播放失败的回调内可以自定义对 DOM 设置播放失败的提示。

**Comment by 2027580893** [comment]
哦，我看文档三四年前的版本有这个功能，但是那些录像截图啥的就没有了

**Comment by 2027580893** [comment]
老哥你这是用什么版本的

**Comment by daiwanxing** [comment]
> 老哥你这是用什么版本的

` "ezuikit-js": "7.7.10"` 这个版本是目前最稳定的了。
