### ISSUE TITLE
按照文档来加载测试的视频提示子账户或萤石用户没有权限

### ISSUE THREAD

**Issue by silentchild** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#171]
const player = new EZUIKit.EZUIKitPlayer({
    id:'domId', // 视频容器ID
    accessToken: 'ra.6fsqjbxv4zeti2ti8v2gkcqd10vayvz4-9gw9msau31-1kqnp0q-talsuppty',
    url: 'ezopen://open.ys7.com/G39444019/1.live',
    width: 300,
    height: 200,
    handleError: (err) => {
      if (err.type === 'handleRunTimeInfoError' && err.data.nErrorCode === 5) {
        // 加密设备密码错误
      }
    },
  });

**Comment by silentchild** [comment]
LinkVideo.vue:47  播放失败，请检查设备及客户端网络 {msg: '子账户或萤石用户没有权限', code: '10031'}

**Comment by silentchild** [comment]
已经按照文档获取了最新的token

**Comment by freeshineit** [comment]
设备被移除了，如果自己有设备可以先用自己的设备进行测试。
