### ISSUE TITLE
Introduce an error  （引入报错）

### ISSUE THREAD

**Issue by Notemo9** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#174]
./node_modules/.pnpm/ezuikit-js@8.0.1-beta.1/node_modules/ezuikit-js/ezuikit.js 27:255236
Module parse failed: Unexpected token (27:255236)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   	 * Date: 2016-08-08
|   	 */
> function(e){var t,i,n,a,r,o,s,l,c,d,u,h,f,x,p,m,_,g,v,y="sizzle"+1*new Date,S=e.document,b=0,P=0,C=oe(),T=oe(),E=oe(),w=function(e,t){return e===t&&(u=!0),0},R={}.hasOwnProperty,I=[],D=I.pop,k=I.push,F=I.push,A=I.slice,M=function(e,t){for(var i=0,n=e.length;i<n;i++)if(e[i]===t)return i;return-1},L="checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",B="[\\x20\\t\\r\\n\\f]",j="(?:\\\\.|[\\w-]|[^\0-\\xa0])+",O="\\["+B+"*("+j+")(?:"+B+"*([*^$|!~]?=)"+B+"*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|("+j+"))|)"+B+"*\\]",N=":("+j+")(?:\\((('(...  
相当于把文件输出了全弄到了终端  这么解决

**Comment by bambooDu** [comment]
哥们 有解决方法没；
![微信图片_20240410190650](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/54257610/4cfcfbdb-d76a-4914-83e2-dd1954516f60)

**Comment by freeshineit** [comment]
https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/issues/151
