### ISSUE TITLE
移动端，全屏后，切回竖屏，界面尺寸没刷新

### ISSUE THREAD

**Issue by LomyCool** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#177]
移动端，全屏后，切回竖屏，界面尺寸没更新会竖屏尺寸
<img width="495" alt="图片" src="https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16275856/77dfc2cd-525e-40a4-b82f-4177759125b7">

**Comment by freeshineit** [comment]
> 移动端，全屏后，切回竖屏，界面尺寸没更新会竖屏尺寸 <img alt="图片" width="495" src="https://private-user-images.githubusercontent.com/16275856/312471990-77dfc2cd-525e-40a4-b82f-4177759125b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzc2MjgsIm5iZiI6MTcxMDMzNzMyOCwicGF0aCI6Ii8xNjI3NTg1Ni8zMTI0NzE5OTAtNzdkZmMyY2QtNTI1ZS00MGE0LWI4MmYtNDE3Nzc1OTEyNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMWRjNTQzMWZkMTY1ZWVlZTRhMTFjODZmOTk4NmE0NGMyYTNkNzZlOTdkOGI0NWJjYTlkNjIyZDQ3OGE0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b1HWVshLi_lJ3dNpaf-jzqW9e8D3TXEXNLSG5EficWU">

请提供一下版本和使用的主题

**Comment by LomyCool** [comment]
> > 移动端，全屏后，切回竖屏，界面尺寸没更新会竖屏尺寸 <img alt="图片" width="495" src="https://private-user-images.githubusercontent.com/16275856/312471990-77dfc2cd-525e-40a4-b82f-4177759125b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzc2MjgsIm5iZiI6MTcxMDMzNzMyOCwicGF0aCI6Ii8xNjI3NTg1Ni8zMTI0NzE5OTAtNzdkZmMyY2QtNTI1ZS00MGE0LWI4MmYtNDE3Nzc1OTEyNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMWRjNTQzMWZkMTY1ZWVlZTRhMTFjODZmOTk4NmE0NGMyYTNkNzZlOTdkOGI0NWJjYTlkNjIyZDQ3OGE0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b1HWVshLi_lJ3dNpaf-jzqW9e8D3TXEXNLSG5EficWU">
> 
> 请提供一下版本和使用的主题
  ezuikit-js:8.0.2
  template:'mobileLive'

**Comment by freeshineit** [comment]
请更新 8.0.8 ，问题已修复
