### ISSUE TITLE
请问到底支不支持？

### ISSUE THREAD

**Issue by kliein** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#181]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/35619815/754a9764-dfda-45b5-bf62-919f2efd8253)
两个链接跳转的文档是一样的！

**Comment by freeshineit** [comment]
> ![image](https://private-user-images.githubusercontent.com/35619815/313640608-754a9764-dfda-45b5-bf62-919f2efd8253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTIyNDksIm5iZiI6MTcxMDgxMTk0OSwicGF0aCI6Ii8zNTYxOTgxNS8zMTM2NDA2MDgtNzU0YTk3NjQtZGZkYS00NWI1LWJmNjItOTE5ZjJlZmQ4MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAxMzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMTZlZjY0M2Q1MTRhOGIzMjZhMThkYjVhMDRhNjNiZTU2NTU0NTU4ODE3MzdjY2U5MWEyYjcxZmM4YzA1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnJF4vzSDuazq0SmL9_CML81NjrPfENlsPQabRtB4iM) 两个链接跳转的文档是一样的！

SDK 本身暂时不支持    需要设备支持 然后调用接口去控制
