### ISSUE TITLE
使用静态引用 会有Uncaught TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by lzf1987** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#184]

**Comment by freeshineit** [comment]
你好 可以贴一下播放地址和报错的截图吗

**Comment by lzf1987** [comment]
在使用npm全局引用以后 都还没进入到业务页面就输入了 
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/33117552/a4f7dcec-9fda-44a4-9b71-270d7d211eea)
看代码是在
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/33117552/35959d23-2fa4-4ff5-9fbd-27dc8fc8fe7b)

**Comment by freeshineit** [comment]
> 在使用npm全局引用以后 都还没进入到业务页面就输入了 ![image](https://private-user-images.githubusercontent.com/33117552/315268121-a4f7dcec-9fda-44a4-9b71-270d7d211eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTIwMzIsIm5iZiI6MTcxMTA5MTczMiwicGF0aCI6Ii8zMzExNzU1Mi8zMTUyNjgxMjEtYTRmN2RjZWMtOWZkYS00NGE0LTliNzEtMjcwZDdkMjExZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMGRkNDViMmNkZDg5MGMyZDVmYjkwNjU4ZDRiMjRlNzk0NmE2N2RlOTVkMmY2MzQ5Yzk2OGU5NDU2Mzc1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VUcJBJtGLTOvMc4-02x4ezJ294d2GOmHifqA4vVov-c) 看代码是在 ![image](https://private-user-images.githubusercontent.com/33117552/315268329-35959d23-2fa4-4ff5-9fbd-27dc8fc8fe7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTIwMzIsIm5iZiI6MTcxMTA5MTczMiwicGF0aCI6Ii8zMzExNzU1Mi8zMTUyNjgzMjktMzU5NTlkMjMtMmZhNC00ZmY1LTlmYmQtMjdkYzhmYzhmZTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4Nzc5ZTNiZTllZTFiYzA0MTExYWViNzg1NTc5NmQ3Yzg2OGM2ZWIyYzRiNjEyMDIwM2IzOWVhMjUwZDJhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1G7P95R8rdHT-bXDFgqyJgRX8HCOfdu08JmgrulWhQ4)


![1711091943554](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16034259/2663289d-a2ed-4fd6-9f92-e6be042da51f)

这是一个别人库里的函数 ，提供一下t的值， 我们排查一下 

https://stackoverflow.com/questions/74767997/failed-to-construct-url-invalid-url

**Comment by lzf1987** [comment]
发现只要页面请求了ajax 这个函数就会拿当前页面请求的URL  去运行一遍这个方法 
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/33117552/8f2e3554-0540-417d-8be6-5bcfd250658a)
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/33117552/5f17cc4f-7ce3-4dcb-bdaa-d5838d9e2366)

**Comment by ly112055** [comment]
请问这个问题解决了吗

**Comment by freeshineit** [comment]
请求方式使用 `/xxxxxx/xxxx`  , 不要使用 `xxxxxx/xxxx` 这种方式  后面会去修复

**Comment by freeshineit** [comment]
请更新 8.0.8 ，问题已修复
