### ISSUE TITLE
import EZUIKit from 'ezuikit-js'; 以及ezuikit-flv报错

### ISSUE THREAD

**Issue by XyhBill** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#187]
in ./~/ezuikit-flv/index.js

Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793)
You may need an appropriate loader to handle this file type.
|   * v5.1.0 - 2020-12-24
|   * (c) Sindre Sorhus; MIT License

已经试过修改webpack.base.conf.js内容 没有效果
![Snipaste_2024-03-27_10-40-13](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/44028272/5bae3318-0c5b-470d-ac6c-555b7ff4477c)

**Comment by freeshineit** [comment]
> in ./~/ezuikit-flv/index.js
> 
> Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793) You may need an appropriate loader to handle this file type. | * v5.1.0 - 2020-12-24 | * (c) Sindre Sorhus; MIT License
> 
> 已经试过修改webpack.base.conf.js内容 没有效果 ![Snipaste_2024-03-27_10-40-13](https://private-user-images.githubusercontent.com/44028272/317102660-5bae3318-0c5b-470d-ac6c-555b7ff4477c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk1MTksIm5iZiI6MTcxMTUwOTIxOSwicGF0aCI6Ii80NDAyODI3Mi8zMTcxMDI2NjAtNWJhZTMzMTgtMGM1Yi00NzBkLWFjNmMtNTU1YjdmZjQ0NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzdmMDBkY2I4MGI5YmNiOGVhNDA0ZmExMGY0ZTc4MzAyNWZkNzZkMmFiYmY2NGVlZjg5MTA3NWNmNWRkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8fbYgX41uH2WXKNALqHGVaoeVztpnC0Vho97jD6xR4)


可以提供一下 node 的版本和webpack 的版本吗

**Comment by XyhBill** [comment]
node:12.11.1 webpack:^2.6.1

**Comment by XyhBill** [comment]
> > in ./~/ezuikit-flv/index.js
> > Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793) You may need an appropriate loader to handle this file type. | * v5.1.0 - 2020-12-24 | * (c) Sindre Sorhus; MIT License
> > 已经试过修改webpack.base.conf.js内容 没有效果 ![Snipaste_2024-03-27_10-40-13](https://private-user-images.githubusercontent.com/44028272/317102660-5bae3318-0c5b-470d-ac6c-555b7ff4477c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk1MTksIm5iZiI6MTcxMTUwOTIxOSwicGF0aCI6Ii80NDAyODI3Mi8zMTcxMDI2NjAtNWJhZTMzMTgtMGM1Yi00NzBkLWFjNmMtNTU1YjdmZjQ0NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzdmMDBkY2I4MGI5YmNiOGVhNDA0ZmExMGY0ZTc4MzAyNWZkNzZkMmFiYmY2NGVlZjg5MTA3NWNmNWRkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8fbYgX41uH2WXKNALqHGVaoeVztpnC0Vho97jD6xR4)
> 
> 可以提供一下 node 的版本和webpack 的版本吗

node:12.11.1 webpack:^2.6.1

**Comment by freeshineit** [comment]
![ScreenCapture20240328100607096](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16034259/a3d8b98b-b32e-4b5a-b771-36b4585fa013)
 试一下

**Comment by XyhBill** [comment]
> > in ./~/ezuikit-flv/index.js
> > Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793) You may need an appropriate loader to handle this file type. | * v5.1.0 - 2020-12-24 | * (c) Sindre Sorhus; MIT License
> > 已经试过修改webpack.base.conf.js内容 没有效果 ![Snipaste_2024-03-27_10-40-13](https://private-user-images.githubusercontent.com/44028272/317102660-5bae3318-0c5b-470d-ac6c-555b7ff4477c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk1MTksIm5iZiI6MTcxMTUwOTIxOSwicGF0aCI6Ii80NDAyODI3Mi8zMTcxMDI2NjAtNWJhZTMzMTgtMGM1Yi00NzBkLWFjNmMtNTU1YjdmZjQ0NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzdmMDBkY2I4MGI5YmNiOGVhNDA0ZmExMGY0ZTc4MzAyNWZkNzZkMmFiYmY2NGVlZjg5MTA3NWNmNWRkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8fbYgX41uH2WXKNALqHGVaoeVztpnC0Vho97jD6xR4)
> 
> 可以提供一下 node 的版本和webpack 的版本吗

我试了下本地引入首先提示我canvas resize fail 但是下一行又输出了我设置的尺寸 resize: width: 412  height: 174
然后报了个错提示无法加载Decoder.js' 具体的报错信息跟我的引入文件路径我贴图
![Snipaste_2024-03-28_10-07-14](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/44028272/42be836e-4f1b-48f0-a183-7ec79a539f36)
![Snipaste_2024-03-28_10-03-50](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/44028272/30cf8278-c1e9-4bf7-a76d-20c35225a173)

**Comment by freeshineit** [comment]
> > > in ./~/ezuikit-flv/index.js
> > > Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793) You may need an appropriate loader to handle this file type. | * v5.1.0 - 2020-12-24 | * (c) Sindre Sorhus; MIT License
> > > 已经试过修改webpack.base.conf.js内容 没有效果 ![Snipaste_2024-03-27_10-40-13](https://private-user-images.githubusercontent.com/44028272/317102660-5bae3318-0c5b-470d-ac6c-555b7ff4477c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk1MTksIm5iZiI6MTcxMTUwOTIxOSwicGF0aCI6Ii80NDAyODI3Mi8zMTcxMDI2NjAtNWJhZTMzMTgtMGM1Yi00NzBkLWFjNmMtNTU1YjdmZjQ0NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzdmMDBkY2I4MGI5YmNiOGVhNDA0ZmExMGY0ZTc4MzAyNWZkNzZkMmFiYmY2NGVlZjg5MTA3NWNmNWRkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8fbYgX41uH2WXKNALqHGVaoeVztpnC0Vho97jD6xR4)
> > 
> > 
> > 可以提供一下 node 的版本和webpack 的版本吗
> 
> 我试了下本地引入首先提示我canvas resize fail 但是下一行又输出了我设置的尺寸 resize: width: 412 height: 174 然后报了个错提示无法加载Decoder.js' 具体的报错信息跟我的引入文件路径我贴图 ![Snipaste_2024-03-28_10-07-14](https://private-user-images.githubusercontent.com/44028272/317567153-42be836e-4f1b-48f0-a183-7ec79a539f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTIyMjAsIm5iZiI6MTcxMTU5MTkyMCwicGF0aCI6Ii80NDAyODI3Mi8zMTc1NjcxNTMtNDJiZTgzNmUtNGYxYi00OGYwLWExODMtN2VjNzlhNTM5ZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NTk2MmJlMDUxYmY0ZDY3YzliMjFiNDFlNTlkMzkyMDZhNTBkNTUwYjUyYTc1MjMzOGI3ZTRjMTFiZGY3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v8CjQZhZsOyssER1E90qfbPKGLeQg-8DLJjH6h5Ep9Q) ![Snipaste_2024-03-28_10-03-50](https://private-user-images.githubusercontent.com/44028272/317567173-30cf8278-c1e9-4bf7-a76d-20c35225a173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTIyMjAsIm5iZiI6MTcxMTU5MTkyMCwicGF0aCI6Ii80NDAyODI3Mi8zMTc1NjcxNzMtMzBjZjgyNzgtYzFlOS00YmY3LWE3NmQtMjBjMzUyMjVhMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZWVjZDVjMDg0MWRhNTFjYWRmOWM4YjA1OWQ3NTZmOTc3ODY1NjdjOGRmYWNlNTJiNmJlZGRiZjlkMjVlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtqB-J5WY5XRYq4hoX_Li7grNJk4hDi45a-_HXRew9M)

资源加载不到， 你有配置 staticPath 吗

**Comment by XyhBill** [comment]
> > > > in ./~/ezuikit-flv/index.js
> > > > Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793) You may need an appropriate loader to handle this file type. | * v5.1.0 - 2020-12-24 | * (c) Sindre Sorhus; MIT License
> > > > 已经试过修改webpack.base.conf.js内容 没有效果 ![Snipaste_2024-03-27_10-40-13](https://private-user-images.githubusercontent.com/44028272/317102660-5bae3318-0c5b-470d-ac6c-555b7ff4477c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk1MTksIm5iZiI6MTcxMTUwOTIxOSwicGF0aCI6Ii80NDAyODI3Mi8zMTcxMDI2NjAtNWJhZTMzMTgtMGM1Yi00NzBkLWFjNmMtNTU1YjdmZjQ0NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzdmMDBkY2I4MGI5YmNiOGVhNDA0ZmExMGY0ZTc4MzAyNWZkNzZkMmFiYmY2NGVlZjg5MTA3NWNmNWRkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8fbYgX41uH2WXKNALqHGVaoeVztpnC0Vho97jD6xR4)
> > > 
> > > 
> > > 可以提供一下 node 的版本和webpack 的版本吗
> > 
> > 
> > 我试了下本地引入首先提示我canvas resize fail 但是下一行又输出了我设置的尺寸 resize: width: 412 height: 174 然后报了个错提示无法加载Decoder.js' 具体的报错信息跟我的引入文件路径我贴图 ![Snipaste_2024-03-28_10-07-14](https://private-user-images.githubusercontent.com/44028272/317567153-42be836e-4f1b-48f0-a183-7ec79a539f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTIyMjAsIm5iZiI6MTcxMTU5MTkyMCwicGF0aCI6Ii80NDAyODI3Mi8zMTc1NjcxNTMtNDJiZTgzNmUtNGYxYi00OGYwLWExODMtN2VjNzlhNTM5ZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NTk2MmJlMDUxYmY0ZDY3YzliMjFiNDFlNTlkMzkyMDZhNTBkNTUwYjUyYTc1MjMzOGI3ZTRjMTFiZGY3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v8CjQZhZsOyssER1E90qfbPKGLeQg-8DLJjH6h5Ep9Q) ![Snipaste_2024-03-28_10-03-50](https://private-user-images.githubusercontent.com/44028272/317567173-30cf8278-c1e9-4bf7-a76d-20c35225a173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTIyMjAsIm5iZiI6MTcxMTU5MTkyMCwicGF0aCI6Ii80NDAyODI3Mi8zMTc1NjcxNzMtMzBjZjgyNzgtYzFlOS00YmY3LWE3NmQtMjBjMzUyMjVhMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZWVjZDVjMDg0MWRhNTFjYWRmOWM4YjA1OWQ3NTZmOTc3ODY1NjdjOGRmYWNlNTJiNmJlZGRiZjlkMjVlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtqB-J5WY5XRYq4hoX_Li7grNJk4hDi45a-_HXRew9M)
> 
> 资源加载不到， 你有配置 staticPath 吗

没有的

**Comment by XyhBill** [comment]
> > > > in ./~/ezuikit-flv/index.js
> > > > Module parse failed: E:\bfworkspace\dhcloud-app\node_modules\ezuikit-flv\index.js Unexpected token (6:61793) You may need an appropriate loader to handle this file type. | * v5.1.0 - 2020-12-24 | * (c) Sindre Sorhus; MIT License
> > > > 已经试过修改webpack.base.conf.js内容 没有效果 ![Snipaste_2024-03-27_10-40-13](https://private-user-images.githubusercontent.com/44028272/317102660-5bae3318-0c5b-470d-ac6c-555b7ff4477c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDk1MTksIm5iZiI6MTcxMTUwOTIxOSwicGF0aCI6Ii80NDAyODI3Mi8zMTcxMDI2NjAtNWJhZTMzMTgtMGM1Yi00NzBkLWFjNmMtNTU1YjdmZjQ0NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMzdmMDBkY2I4MGI5YmNiOGVhNDA0ZmExMGY0ZTc4MzAyNWZkNzZkMmFiYmY2NGVlZjg5MTA3NWNmNWRkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8fbYgX41uH2WXKNALqHGVaoeVztpnC0Vho97jD6xR4)
> > > 
> > > 
> > > 可以提供一下 node 的版本和webpack 的版本吗
> > 
> > 
> > 我试了下本地引入首先提示我canvas resize fail 但是下一行又输出了我设置的尺寸 resize: width: 412 height: 174 然后报了个错提示无法加载Decoder.js' 具体的报错信息跟我的引入文件路径我贴图 ![Snipaste_2024-03-28_10-07-14](https://private-user-images.githubusercontent.com/44028272/317567153-42be836e-4f1b-48f0-a183-7ec79a539f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTIyMjAsIm5iZiI6MTcxMTU5MTkyMCwicGF0aCI6Ii80NDAyODI3Mi8zMTc1NjcxNTMtNDJiZTgzNmUtNGYxYi00OGYwLWExODMtN2VjNzlhNTM5ZjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NTk2MmJlMDUxYmY0ZDY3YzliMjFiNDFlNTlkMzkyMDZhNTBkNTUwYjUyYTc1MjMzOGI3ZTRjMTFiZGY3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v8CjQZhZsOyssER1E90qfbPKGLeQg-8DLJjH6h5Ep9Q) ![Snipaste_2024-03-28_10-03-50](https://private-user-images.githubusercontent.com/44028272/317567173-30cf8278-c1e9-4bf7-a76d-20c35225a173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTIyMjAsIm5iZiI6MTcxMTU5MTkyMCwicGF0aCI6Ii80NDAyODI3Mi8zMTc1NjcxNzMtMzBjZjgyNzgtYzFlOS00YmY3LWE3NmQtMjBjMzUyMjVhMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZWVjZDVjMDg0MWRhNTFjYWRmOWM4YjA1OWQ3NTZmOTc3ODY1NjdjOGRmYWNlNTJiNmJlZGRiZjlkMjVlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtqB-J5WY5XRYq4hoX_Li7grNJk4hDi45a-_HXRew9M)
> 
> 资源加载不到， 你有配置 staticPath 吗

目前重新本地引入了下是可以了 可能是项目本地缓存的问题，我是把官方的vue2-demo里ezuikit.js版本跟新到8.0.2之后再把js文件跟配套文件复制到本地引入，如果使用npm后import还是会在控制台输出不知道哪个js文件的内容不管是ezuikit.js还是ezuikit-flv.js都是这样，麻烦大佬后面解决下
