### ISSUE TITLE
云台控制轮盘怎么调用的?

### ISSUE THREAD

**Issue by m3074670391** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#191]
页面调试的时候这个轮盘就会偶尔出现，请问一下调用的相关代码是什么？

**Comment by m3074670391** [comment]
> 页面调试的时候这个轮盘就会偶尔出现，请问一下调用的相关代码是什么？

**Comment by freeshineit** [comment]
> 页面调试的时候这个轮盘就会偶尔出现，请问一下调用的相关代码是什么？

如果你说的轮盘是云台控制的话，以下几种情况会出现

1. pvLive 主题下 点击云台图标会在展示云台控件
 ![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16034259/9e28355b-b5c2-4e67-8380-abf5f0e7fcc3)
2. mobileLive 主题默认展示

回放主题不展示

**Comment by freeshineit** [comment]
> 页面调试的时候这个轮盘就会偶尔出现，请问一下调用的相关代码是什么？

相关云台控制的接口 （需要设备本身支持）
https://open.ys7.com/help/679
https://open.ys7.com/help/680
