### ISSUE TITLE
themeData 清晰度切换不生效

### ISSUE THREAD

**Issue by bambooDu** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#194]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/54257610/584d53b9-7961-480e-8b9b-286adf1d113b)
ezopen参数的地址 1.live 在切换 hd高清时还是这个地址；清晰度没任何变化；

**Comment by KWalking** [comment]
我也是最近发现这种情况，编译后的代码完全无法调试，也不知道什么情况，希望能尽快修复

**Comment by freeshineit** [comment]
切换的逻辑进行了更新， 现在是根据设备的能力集（能力集需要设备进行报备）进行判断的。如果设备能力集不支持子码流 ，切换则不生效。 已经和产品沟通了 后面会进行优化

**Comment by bambooDu** [comment]
嗯 只能手动play(1.hd.live)切换高清地址。
