### ISSUE TITLE
React18.2.0中调用报错

### ISSUE THREAD

**Issue by houguang** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#200]
![image](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/1720347/ef95f131-7235-45c7-8fd1-e45e2ae670bf)

**调用时画面能正常显示,但是报上面的错误**

### 环境
- react 18.2.0
- node 20.10.0
- "ezuikit-js": "^8.0.3"

**Comment by freeshineit** [comment]
新版已解决
