### ISSUE TITLE
移动端点击全屏

### ISSUE THREAD

**Issue by LiJinWeb** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#208]
![Snipaste_2024-05-10_16-57-43](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/164292582/383925d8-34d7-4a8f-bbe0-22222b1c31a2)

**Comment by LiJinWeb** [comment]
样式不对 不知道有什么处理方法

**Comment by freeshineit** [comment]
> 样式不对 不知道有什么处理方法

那个版本 ， 看样式时来老版了， 你可以使用新版试一下（https://www.npmjs.com/package/ezuikit-js）， 还有就是体验设备被移除了 现在可能不能使用。如果有设备可以使用自己的设备。如果没有设备， 留一下邮箱我单独发你一台试试。

**Comment by Lwj-1024** [comment]
同样的问题 解决了吗 我使用的就是8.0.5的版本

**Comment by freeshineit** [comment]
> 同样的问题 解决了吗 我使用的就是8.0.5的版本

 系统和浏览器说一下

**Comment by Lwj-1024** [comment]
> > 同样的问题 解决了吗 我使用的就是8.0.5的版本
> 
> 系统和浏览器说一下

浏览器中F12打开移动端模拟 再点击全屏就会复现 全屏之后如果是回放 样式会错乱 视频播放器会盖住时间轴 并且无法再缩回小屏

**Comment by Lwj-1024** [comment]
> > > 同样的问题 解决了吗 我使用的就是8.0.5的版本
> > 
> > 
> > 系统和浏览器说一下
> 
> 浏览器中F12打开移动端模拟 再点击全屏就会复现 全屏之后如果是回放 样式会错乱 视频播放器会盖住时间轴 并且无法再缩回小屏

![Uploading 1721114036798.jpg…]()

**Comment by freeshineit** [comment]
请更新 8.0.8 ，问题已修复
