### ISSUE TITLE
7.7.10 版本执行 play() 界面未能成功播放视频

### ISSUE THREAD

**Issue by daiwanxing** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#209]
**bug 描述(Describe the bug)**

对bug是什么的清晰简洁的描述。 (A clear and concise description of what the bug is.)

**复现(To Reproduce)**

再现步骤(Steps to reproduce the behavior):

**预期行为(Expected behavior)**

对你期望发生的事情的清晰简洁的描述。 (A clear and concise description of what you expected to happen.)

**截图(Screenshots)**

如果适用，请添加屏幕截图以帮助解释您的问题。 (If applicable, add screenshots to help explain your problem.)

**PC 请填写以下信息 (please complete the following information):**

**mobile 请填写以下信息 (please complete the following information):**

**附加上下文(Additional context)**

在此处添加有关该问题的任何其他上下文。 (Add any other context about the problem here.)

**Comment by daiwanxing** [comment]
草，我才发现你们的视频挂载的容器不能出现数字么。。。

我把 ` _player_${Math.random() * 1000}` 换成字符串 就行了

**Comment by freeshineit** [comment]
> 草，我才发现你们的视频挂载的容器 id 不能出现数字么。。。
> 
> 我把 ` _player_${Math.random() * 1000}` 换成字符串 就行了

容器的id 其实就是 dom 的id ,   dom 上的属性都是字符串， 这样使用document.getElementById 才能匹配的到
