### ISSUE TITLE
集成EZUIKIT SDK与video.js 的兼容性问题，创建video.js的实例视频请求的发起者（initiator）竟然是ezuikit-js.js

### ISSUE THREAD

**Issue by ZQlmh** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#212]
**bug 描述(Describe the bug)**

集成EZUIKIT SDK并引入video.js 在同一页面动态创建两个类型的实例，使用video.js创建的实例加载flv视频流，发现视频请求的发起者（initiator）竟然是ezuikit-js.js，导致video.js的实例未被正确实例化。EZUIKit 的脚本文件会自动检测页面中的视频元素并干扰视频请求吗？

**复现(To Reproduce)**

再现步骤(Steps to reproduce the behavior):

1. 集成EZUIKIT SDK
2. 同时引入video.js库
3. 根据视频类型分别动态创建EZUIKit.EZUIKitPlayer实例及videojs实例
4. 运行demo发现videojs的实例请求发起者（initiator）竟然是ezuikit-js.js，导致videojs实例化异常，无法进行dispose操作

**预期行为(Expected behavior)**

期望各实例操作互不干扰，互相隔离

**截图(Screenshots)**

![WechatIMG6684](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16482781/05cae6a3-41e2-4e70-bf87-d402e878186e)
![WechatIMG6685](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16482781/83d2e3c5-e783-4a7e-a791-95dc33452b34)
![WechatIMG6686](https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/assets/16482781/654ef7da-51e6-40f1-997b-c5ce08e6ace7)

**PC 请填写以下信息 (please complete the following information):**

- OS: [14.4.1 (23E224)]
- Browser [chrome]
- Version [版本 124.0.6367.208（正式版本）]

**Comment by ZQlmh** [comment]
@freeshineit 大佬这个问题什么时候解决，有提上日程吗？

**Comment by freeshineit** [comment]
> @freeshineit 大佬这个问题什么时候解决，有提上日程吗？

下周内测 ， 下下周应该可以发布

**Comment by freeshineit** [comment]
请更新 8.0.8 ，问题已修复   @ZQlmh
