### ISSUE TITLE
为 ezuikit-js 添加类型定义包

### ISSUE THREAD

**Issue by daiwanxing** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#215]
因为公司很多项目用到了 `ezuikit-js`，且项目都是用 Typescript 开发的。

但由于 `ezuikit-js` 并非用 TS 编写的，而且非 ESM。所以在 TS 项目内使用 `ezuikit-js` 时需要在 `index.d.ts` 声明一行 `declare module 'ezuikit-js'` 才能修复找不到模块的错误。并且由于缺乏类型声明，编辑器也不会有智能提示。

我相信其他开发者在使用 TS 开发项目用到这个包也会遇到我这样的场景，于是我自己参照仓库的 README 以及 [萤石文档](https://open.ys7.com/help/31)  编写了一个类型定义包，托管到 [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)。

不知道官方能否支持并加入到这个 package 的 owner。

附 PR 链接：https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69786

**Comment by freeshineit** [comment]
非常感谢  我们后面会在构建时生成生命文件和支持 esm

**Comment by daiwanxing** [comment]
> 非常感谢 我们后面会在构建时生成生命文件和支持 esm

好的，目前能先帮我 review 下吗🤣，后续的更新如果捆绑了类型的话再从 DefinitelyTyped 移除也不迟。
