### ISSUE TITLE
> > 同样的问题 解决了吗 我使用的就是8.0.5的版本

### ISSUE THREAD

**Issue by Lwj-1024** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#227]
> > 同样的问题 解决了吗 我使用的就是8.0.5的版本
> 
> 系统和浏览器说一下

浏览器中F12打开移动端模拟 再点击全屏就会复现 全屏之后如果是回放 样式会错乱 视频播放器会盖住时间轴 并且无法再缩回小屏

_Originally posted by @Lwj-1024 in https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/issues/208#issuecomment-2232214426_

**Comment by Lwj-1024** [comment]
![1721114036798](https://github.com/user-attachments/assets/7c2a1325-56aa-4bc9-9ee5-ef126657bc43)
报错示例

**Comment by Lwj-1024** [comment]
![a16d4eacec619214ee4f7df30675683](https://github.com/user-attachments/assets/4a684b20-50b3-4a6d-88d9-23435e9c2c36)
报错示例代码

**Comment by Lwj-1024** [comment]
![image](https://github.com/user-attachments/assets/73d61c85-c42c-4eb3-94d6-7b4f13862f7c)
源代码这个地方没有加播放清晰度的下拉框的非空判断 实际移动端rec是没有这个下拉框的 但是他会必定到这里去修改这个下拉的样式 导致报错 全屏和恢复的时候都修改一下即可 
再配上一份萤石技术支撑的回复.....
![image](https://github.com/user-attachments/assets/30cafbe7-bb90-47ed-9830-a723ec78138b)

**Comment by freeshineit** [comment]
请更新  8.0.8 ，问题已修复
