### ISSUE TITLE
 drop_console: true时白屏

### ISSUE THREAD

**Issue by qykhhhhhhh** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#228]
**bug 描述(Describe the bug)**

引入ezukit，打包配置 drop_console: true时，页面会白屏
原因应该是ezukit代码里console.log和ee.log杂糅到了业务逻辑里，当console.log被屏蔽时，影响正常使用，希望owner尽快复现与修复，我看5月就有issue了

**Comment by freeshineit** [comment]
terser 的bug  已经提给他们了 https://github.com/terser/terser/issues/1515,  一个第三方库导致的， 后面我们也会去修复

**Comment by freeshineit** [comment]
terser 官方已经修复这个问题 请升级最新版 terser 
https://github.com/terser/terser/issues/1515#event-14360850273
