### ISSUE TITLE
为什么听筒和麦不能同时开启？

### ISSUE THREAD

**Issue by suzhenghui-sky** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#231]
**bug 描述(Describe the bug)**

对bug是什么的清晰简洁的描述。 (A clear and concise description of what the bug is.)
为什么听筒和麦不能同时开启？版本  "ezuikit-js": "7.7.10"

**复现(To Reproduce)**

再现步骤(Steps to reproduce the behavior):
1.点击麦克风时候，听筒就会关闭，只有关闭了麦克风，听筒才能开启。

**预期行为(Expected behavior)**
麦和听筒应该可以同时开启

对你期望发生的事情的清晰简洁的描述。 (A clear and concise description of what you expected to happen.)
为什么听筒和麦不能同时开启？

**截图(Screenshots)**

如果适用，请添加屏幕截图以帮助解释您的问题。 (If applicable, add screenshots to help explain your problem.)

**PC 请填写以下信息 (please complete the following information):**

**mobile 请填写以下信息 (please complete the following information):**

**附加上下文(Additional context)**

在此处添加有关该问题的任何其他上下文。 (Add any other context about the problem here.)

**Comment by freeshineit** [comment]
不太清楚你说的听筒是什么意思， 听筒是视频的声音还是对讲的声音。

对讲的情况下 视频的音频是强制关掉的， 如果是全双工的设备 开启对讲两端都是可以听到声音的， 声音单独来自对讲通道

**Comment by Yayhub** [comment]
确实对讲录制和外放声音不能同时开启，萤石云app上可以做到
