### ISSUE TITLE
有性能指标么，比如多少清晰度，支持多少路同时取流

### ISSUE THREAD

**Issue by xxholly32** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#236]
**bug 描述(Describe the bug)**

项目上有16路的需求，但不确定是否能够支持，PS 海康内部员工

**Comment by freeshineit** [comment]
最多支持16 路，  HikLink:  shaoqiangqiang

> **bug 描述(Describe the bug)**
> 
> 项目上有16路的需求，但不确定是否能够支持，PS 海康内部员工

最多支持16 路，  HikLink:  shaoqiangqiang
