### ISSUE TITLE
调用浏览器内置API进入全屏后，再播放摄像头时，会出现播放画布异常

### ISSUE THREAD

**Issue by ZhouJieLunJay** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#240]
**bug 描述(Describe the bug)**

调用浏览器内置API进入全屏后，再播放摄像头时，会出现播放画布异常

再现步骤(Steps to reproduce the behavior):

1.先进入浏览器全屏状态
2. 初始化摄像头与播放

![微信截图_20240801110520](https://github.com/user-attachments/assets/5f5f4575-be52-4bef-87f9-da50a468be1f)

**Comment by saberonthemic** [comment]
怎么解决的

**Comment by freeshineit** [comment]
> 怎么解决的

升级版本了吗 

逻辑：全屏监听判断具体全屏的节点，才会去做下一步操作
