### ISSUE TITLE
ezui protocol format error in base-demo

### ISSUE THREAD

**Issue by dineshimatrix** [Ezviz-OpenBiz/EZUIKit-JavaScript-npm#266]
I'm followed the steps in readme in base-demo and installed nodejs and npm v8.0.0. when i try to run the http-server, the page is opening in browser but when init button is clicked, the player got loaded and shows "The ezopen protocol format error". but i've directly edited the html and placed my access token and URL which is generated from http APIs. still no success.

![image](https://github.com/user-attachments/assets/ace7e2a7-8442-4fa5-b891-338de2c3c40c)

Help me to resolve this issue.

**Comment by freeshineit** [comment]
1. Check if there are spaces in the playback address
2. Check env.domain

**Comment by freeshineit** [comment]
![ScreenCapture20241028102751549](https://github.com/user-attachments/assets/7645c9bc-a223-4148-bcc5-e8b6fff53845)

You can configure this domain https://iindiaopen.ezvizlife.com
